version: '3.1'

services:
  appliances:
    build: ./appliances
    container_name: appliances
    volumes:
      - ./appliances/src:/home/app/src
    command: npm run start
  auth:
    build: ./auth
    container_name: auth
    volumes:
      - ./auth/src:/home/app/src
    command: npm run start

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 8080:8080
    links:
      - appliances
      - auth
